added LINEARFIT SPLINELINEARFIT AKIMASPLINEFIT
senx/warp10-ext-interpolation pull request #1
Opened 2022-09-09 09:14 UTC by pi-r-p

2022-09-09 09:49 UTC, randomboolean commented
- The naming has to be revised since Akima and spline interpolators are not linear interpolators.
- I believe it is a better idea to separate the fit (obtaining function parameters) and the creation of the function in two speerate functions, in the same manner it is done in the main library with POLYFIT and POLYFUNC
- This pose the question of the naming convention given to functions of this extension, since for now, BICUBICFIT, TRICUBICFIT and MICROSPHEREFIT outputs directly a function, unlike POLYFIT.
- Also, POLYFIT and POLYFUNC are 1-d interpolators on the ticks, so maybe we would have to name the functions of this PR something like: VALUEPOLYFIT, VALUEPOLYFUNC, VALUESPLINEFIT, VALUESPLINEFUNC, VALUEAKIMAFIT, VALUEAKIMAFUNC

2022-09-13 20:36 UTC, pi-r-p commented
I will update readme and doc once we converge.
For the moment, I did not created the "FIT" function for snapshot 1D interpolator, I clone the input list.

2022-10-07 15:47 UTC, randomboolean requested changes

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolationWarpScriptExtension.java
> +
remove a line break

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolationWarpScriptExtension.java
> +
I wonder if it is relevant to specify the dimensionality in the name. I'd rather only put it in the documentation.

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolationWarpScriptExtension.java
> +  public static final String INTERPOLATOR_1_D_AKIMA = "INTERPOLATOR.1D.AKIMA";
Remove  underscore between number and 'D'

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/BicubicInterpolatorSmallGrid.java
> + */
mention the source and describe the changes

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/BicubicInterpolatorSmallGrid.java
> +public class BicubicInterpolatorSmallGrid
The name is not appropriate. Why small grid ?

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/BicubicInterpolatorSmallGrid.java
> +
remove a line break

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/TricubicInterpolatorSmallGrid.java
> +
remove a line break

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/TricubicInterpolatorSmallGrid.java
> +
remove a line break

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/TricubicInterpolatorSmallGrid.java
> +
remove a line break

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/TricubicInterpolatorSmallGrid.java
> +public class TricubicInterpolatorSmallGrid
mention source, describe changes, and give a more appropriate name

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorTricubic.java
> +      }
add a line break

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorTricubic.java
> +        return new Object[] {Long.MAX_VALUE, GeoTimeSerie.NO_LOCATION, GeoTimeSerie.NO_ELEVATION, null};
use tick instead of Long.MAX_VALUE (only not to overwrite a tick in a very marginal case)

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorLinear.java
> +  public static enum TYPE {
Modifier 'static' is redundant for inner enums

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorLinear.java
> +    LINEAR,SPLINE, AKIMA
missing a space

2022-10-07 15:47 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorLinear.java
> +      if (1 != values.length) {
also need to handle case 0 == values.length separately for empty buckets

2022-10-07 15:53 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorBicubic.java
> +    BicubicInterpolatingFunction function = (new BicubicInterpolatorSmallGrid()).interpolate(xval, yval, fval);
There should be an optional parameter to choose a type of border effect, so that users can revert to the behavior of original implementation if they need to

2023-09-26 11:43 UTC, randomboolean commented on src/main/java/io/warp10/ext/interpolation/InterpolatorLinear.java
> +      if (1 != values.length) {
Not relevant here since function is applied on values and not on ticks.
Applying on tick as a mapper will be supported with a future PR

2023-09-27 09:08 UTC, randomboolean approved these changes

2023-10-11 14:00 UTC, merged